config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'tweets#index'
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: 'top' }, { id: 2, name: 'jg' }, { id: 3, name: 'mid' },
    { id: 4, name: 'sup' }, { id: 5, name: 'bot' }, 

  ]
end

app/models/rank.rb
class Rank < ActiveHash::Base
  self.data = [
    { id: 1, name: 'iron4' }, { id: 2, name: 'iron3' }, { id: 3, name: 'iron2' }, { id: 4, name: 'iron1' }, 
    { id: 5, name: 'bronze4' }, { id: 6, name: 'bronze3' }, { id: 7, name: 'bronze2' }, { id: 8, name: 'bronze1' }, 
    { id: 9, name: 'silver4' }, { id: 10, name: 'silver3' }, { id: 11, name: 'silver2' }, { id: 12, name: 'silver1' }, 
    { id: 13, name: 'gold4' }, { id: 14, name: 'gold3' }, { id: 15, name: 'gold2' }, { id: 16, name: 'gold1' }, 
    { id: 17, name: 'plat4' }, { id: 18, name: 'plat3' }, { id: 19, name: 'plat2' }, { id: 20, name: 'plat1' }, 
    { id: 21, name: 'dia4' }, { id: 22, name: 'dia3' }, { id: 23, name: 'dia2' }, { id: 24, name: 'dia1' },
    { id: 25, name: 'master' }, { id: 26, name: 'grandmaster' }, { id: 27, name: 'challenger' }
  ]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :rank
  belongs_to_active_hash :weekday
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweet
  validates :nickname, presence: true

end

app/models/weekday.rb
class Weekday < ActiveHash::Base
  self.data = [
    { id: 1, name: '土日祝日' }, { id: 2, name: '平日' },{ id: 3, name: '毎日' } 
    

  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :position_id, :rank_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
     redirect_to user_session_path
    else
     render 'new'
    end
  end

private

  def tweet_params
    params.require(:tweet).permit(:toprank_id, :jgrank_id, :midrank_id, :suprank_id, :botrank_id, :detail, :teamname, :starttime, :endtime, :weekday_id).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Btweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            
          </div>
          <% if user_signed_in? %>
             <div class="nav__right"> 
              <%= link_to "トップページ", root_path, class: :nav__logout %>
              <%= link_to "新規投稿", new_tweet_path, class: :nav__btn %>
              <%= link_to current_user.nickname, "#", class: :nav__logout %>
              <%= link_to "ログアウト", destroy_user_session_path, class: :nav__logout %>
             </div> 
         <% else %>
            <div class="nav__right">
              <%= link_to "トップページ", root_path, class: :nav__logout %> 
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<% @tweets.each do |tweet|%>
 <div class="team">
  <%= image_tag "rank#{tweet.toprank_id}.png"%>
  <%= image_tag "rank#{tweet.jgrank_id}.png"%>
  <%= image_tag "rank#{tweet.midrank_id}.png"%>
  <%= image_tag "rank#{tweet.suprank_id}.png"%>
  <%= image_tag "rank#{tweet.botrank_id}.png"%>
   <div class="detail">
    <div class="user">
     投稿者　　　: <%=tweet.user.nickname%>
    </div>
    <div calss="name">
     チーム名　　: <%=tweet.teamname%>
    </div>
    <div calss="weekday">
     活動日　　　: <%=tweet.weekday[:name]%>
    </div>
    <div class="time">
     コアタイム　: <%=tweet.starttime.strftime("%H:%M")%> ~ <%=tweet.endtime.strftime("%H:%M")%>
    </div>
    <div class="comment">
     詳細説明　　: <%=tweet.detail%>
     </div>
   </div>
   

 </div>


<%end%>

app/views/tweets/new.html.erb
<%= form_with(model: @tweet, url: tweets_path, local: true) do |f|%>
  <div class="field">
    <%= f.label :teamname, "チーム名" %><br />
    <%= f.text_field :teamname %>
  </div>

    <div class="field">
    <%= f.label :weekday, "活動日" %><br />
    <%= f.collection_select(:weekday_id, Weekday.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
  </div>

  <div class="field">
    <%= f.label :starttime, "開始時刻~終了時刻" %><br />
    <%= f.time_field :starttime %>〜〜
    <%= f.time_field :endtime %>
  </div>
 
  <div class="field">
    <%= f.label :toplank, "TOP RANK" %><br />
    <%= f.collection_select(:toprank_id, Rank.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
  </div>

   <div class="field">
    <%= f.label :jglank, "JG RANK" %><br />
    <%= f.collection_select(:jgrank_id, Rank.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
  </div>

   <div class="field">
    <%= f.label :midlank, "MID RANK" %><br />
    <%= f.collection_select(:midrank_id, Rank.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
  </div>

   <div class="field">
    <%= f.label :suplank, "SUP RANK" %><br />
    <%= f.collection_select(:suprank_id, Rank.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
  </div>

   <div class="field">
    <%= f.label :botlank, "BOT RANK" %><br />
    <%= f.collection_select(:botrank_id, Rank.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
  </div>

  <div class="field">
    <%= f.label :detail, "チーム紹介" %><br />
    <%= f.text_area :detail %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>

<% end %>